#!/bin/bash

# Integration test for nrpe/check_nrpe
# Should be run only on machines which do NOT have Nagios installed 
# and which do not have an enabled firewall.

cd sample-config
echo >> nrpe.cfg # Hopefully this is a newline! I think nrpe.cfg ends in a newling anyways.
echo 'check_command[check_test]=../check_yes.sh' >> nrpe.cfg

cat nrpe.cfg

# Make sure the directory exists such that nrpe can create the nrpe.pid file in the default location
mkdir /usr/ || true
mkdir /usr/local || true
mkdir /usr/local/nagios || true
mkdir /usr/local/nagios/var || true

# Make sure nagios user exists
useradd nagios
echo "nagios" | passwd nagios --stdin

# Make a plugin
cd ..
touch check_yes.sh
echo 'echo OK' >> check_yes.sh

# Give nagios control of plugins
chown nagios check_yes.sh

# Start running the NRPE daemon to accept commands
cd src
./nrpe -c ../sample-config/nrpe.cfg -d

# Try to check_nrpe with our check_test command/check_yes.sh plugin
./check_nrpe -H 127.0.0.1 -c check_test

exit 0
